// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: internal/app/transport/grpc/proto/shortener.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type HandlePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginURL string `protobuf:"bytes,1,opt,name=originURL,proto3" json:"originURL,omitempty"`
}

func (x *HandlePostRequest) Reset() {
	*x = HandlePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePostRequest) ProtoMessage() {}

func (x *HandlePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePostRequest.ProtoReflect.Descriptor instead.
func (*HandlePostRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *HandlePostRequest) GetOriginURL() string {
	if x != nil {
		return x.OriginURL
	}
	return ""
}

type HandlePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ShortenURL string `protobuf:"bytes,2,opt,name=shortenURL,proto3" json:"shortenURL,omitempty"`
}

func (x *HandlePostResponse) Reset() {
	*x = HandlePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePostResponse) ProtoMessage() {}

func (x *HandlePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePostResponse.ProtoReflect.Descriptor instead.
func (*HandlePostResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *HandlePostResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandlePostResponse) GetShortenURL() string {
	if x != nil {
		return x.ShortenURL
	}
	return ""
}

type HandleGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL string `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
}

func (x *HandleGetRequest) Reset() {
	*x = HandleGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGetRequest) ProtoMessage() {}

func (x *HandleGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGetRequest.ProtoReflect.Descriptor instead.
func (*HandleGetRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *HandleGetRequest) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type HandleGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	OriginURL string `protobuf:"bytes,2,opt,name=originURL,proto3" json:"originURL,omitempty"`
}

func (x *HandleGetResponse) Reset() {
	*x = HandleGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGetResponse) ProtoMessage() {}

func (x *HandleGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGetResponse.ProtoReflect.Descriptor instead.
func (*HandleGetResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *HandleGetResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandleGetResponse) GetOriginURL() string {
	if x != nil {
		return x.OriginURL
	}
	return ""
}

type SetURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL  string `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
	OriginURL string `protobuf:"bytes,2,opt,name=originURL,proto3" json:"originURL,omitempty"`
}

func (x *SetURLsResponse) Reset() {
	*x = SetURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetURLsResponse) ProtoMessage() {}

func (x *SetURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetURLsResponse.ProtoReflect.Descriptor instead.
func (*SetURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *SetURLsResponse) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

func (x *SetURLsResponse) GetOriginURL() string {
	if x != nil {
		return x.OriginURL
	}
	return ""
}

type HandleGetUserURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetURLs []*SetURLsResponse `protobuf:"bytes,1,rep,name=setURLs,proto3" json:"setURLs,omitempty"`
}

func (x *HandleGetUserURLsResponse) Reset() {
	*x = HandleGetUserURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleGetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGetUserURLsResponse) ProtoMessage() {}

func (x *HandleGetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*HandleGetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *HandleGetUserURLsResponse) GetSetURLs() []*SetURLsResponse {
	if x != nil {
		return x.SetURLs
	}
	return nil
}

type CorrelationURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalURL string `protobuf:"bytes,2,opt,name=originalURL,proto3" json:"originalURL,omitempty"`
}

func (x *CorrelationURLRequest) Reset() {
	*x = CorrelationURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorrelationURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationURLRequest) ProtoMessage() {}

func (x *CorrelationURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationURLRequest.ProtoReflect.Descriptor instead.
func (*CorrelationURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *CorrelationURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CorrelationURLRequest) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

type CorrelationURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortURL string `protobuf:"bytes,2,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
}

func (x *CorrelationURLResponse) Reset() {
	*x = CorrelationURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorrelationURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationURLResponse) ProtoMessage() {}

func (x *CorrelationURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationURLResponse.ProtoReflect.Descriptor instead.
func (*CorrelationURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *CorrelationURLResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CorrelationURLResponse) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type HandlePostShortenBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationURL []*CorrelationURLRequest `protobuf:"bytes,1,rep,name=correlationURL,proto3" json:"correlationURL,omitempty"`
}

func (x *HandlePostShortenBatchRequest) Reset() {
	*x = HandlePostShortenBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlePostShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePostShortenBatchRequest) ProtoMessage() {}

func (x *HandlePostShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePostShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*HandlePostShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *HandlePostShortenBatchRequest) GetCorrelationURL() []*CorrelationURLRequest {
	if x != nil {
		return x.CorrelationURL
	}
	return nil
}

type HandlePostShortenBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         int32                     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	CorrelationURL []*CorrelationURLResponse `protobuf:"bytes,2,rep,name=correlationURL,proto3" json:"correlationURL,omitempty"`
}

func (x *HandlePostShortenBatchResponse) Reset() {
	*x = HandlePostShortenBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlePostShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePostShortenBatchResponse) ProtoMessage() {}

func (x *HandlePostShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePostShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*HandlePostShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *HandlePostShortenBatchResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandlePostShortenBatchResponse) GetCorrelationURL() []*CorrelationURLResponse {
	if x != nil {
		return x.CorrelationURL
	}
	return nil
}

var File_internal_app_transport_grpc_proto_shortener_proto protoreflect.FileDescriptor

var file_internal_app_transport_grpc_proto_shortener_proto_rawDesc = []byte{
	0x0a, 0x31, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x22, 0x0e,
	0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26,
	0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x31, 0x0a, 0x11, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x55, 0x52, 0x4c, 0x22, 0x4c, 0x0a, 0x12, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x22, 0x2e, 0x0a, 0x10, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x49, 0x0a, 0x11, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x55, 0x52,
	0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x55,
	0x52, 0x4c, 0x22, 0x4b, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x55, 0x52, 0x4c, 0x22,
	0x51, 0x0a, 0x19, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x07,
	0x73, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x52, 0x4c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x73, 0x65, 0x74, 0x55, 0x52,
	0x4c, 0x73, 0x22, 0x49, 0x0a, 0x15, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x22, 0x44, 0x0a,
	0x16, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x52, 0x4c, 0x22, 0x69, 0x0a, 0x1d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0e,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x22, 0x83,
	0x01, 0x0a, 0x1e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x49, 0x0a, 0x0e, 0x63, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x43, 0x6f,
	0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x55, 0x52, 0x4c, 0x32, 0x9b, 0x03, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x12, 0x38, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x2e, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x52, 0x0a, 0x11, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x52, 0x4c, 0x73, 0x12, 0x17, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a, 0x16, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x28, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_app_transport_grpc_proto_shortener_proto_rawDescOnce sync.Once
	file_internal_app_transport_grpc_proto_shortener_proto_rawDescData = file_internal_app_transport_grpc_proto_shortener_proto_rawDesc
)

func file_internal_app_transport_grpc_proto_shortener_proto_rawDescGZIP() []byte {
	file_internal_app_transport_grpc_proto_shortener_proto_rawDescOnce.Do(func() {
		file_internal_app_transport_grpc_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_app_transport_grpc_proto_shortener_proto_rawDescData)
	})
	return file_internal_app_transport_grpc_proto_shortener_proto_rawDescData
}

var file_internal_app_transport_grpc_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_app_transport_grpc_proto_shortener_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),                   // 0: shortener.EmptyRequest
	(*PingResponse)(nil),                   // 1: shortener.PingResponse
	(*HandlePostRequest)(nil),              // 2: shortener.HandlePostRequest
	(*HandlePostResponse)(nil),             // 3: shortener.HandlePostResponse
	(*HandleGetRequest)(nil),               // 4: shortener.HandleGetRequest
	(*HandleGetResponse)(nil),              // 5: shortener.HandleGetResponse
	(*SetURLsResponse)(nil),                // 6: shortener.SetURLsResponse
	(*HandleGetUserURLsResponse)(nil),      // 7: shortener.HandleGetUserURLsResponse
	(*CorrelationURLRequest)(nil),          // 8: shortener.CorrelationURLRequest
	(*CorrelationURLResponse)(nil),         // 9: shortener.CorrelationURLResponse
	(*HandlePostShortenBatchRequest)(nil),  // 10: shortener.HandlePostShortenBatchRequest
	(*HandlePostShortenBatchResponse)(nil), // 11: shortener.HandlePostShortenBatchResponse
}
var file_internal_app_transport_grpc_proto_shortener_proto_depIdxs = []int32{
	6,  // 0: shortener.HandleGetUserURLsResponse.setURLs:type_name -> shortener.SetURLsResponse
	8,  // 1: shortener.HandlePostShortenBatchRequest.correlationURL:type_name -> shortener.CorrelationURLRequest
	9,  // 2: shortener.HandlePostShortenBatchResponse.correlationURL:type_name -> shortener.CorrelationURLResponse
	0,  // 3: shortener.Shortener.Ping:input_type -> shortener.EmptyRequest
	2,  // 4: shortener.Shortener.HandlePost:input_type -> shortener.HandlePostRequest
	4,  // 5: shortener.Shortener.HandleGet:input_type -> shortener.HandleGetRequest
	0,  // 6: shortener.Shortener.HandleGetUserURLs:input_type -> shortener.EmptyRequest
	10, // 7: shortener.Shortener.HandlePostShortenBatch:input_type -> shortener.HandlePostShortenBatchRequest
	1,  // 8: shortener.Shortener.Ping:output_type -> shortener.PingResponse
	3,  // 9: shortener.Shortener.HandlePost:output_type -> shortener.HandlePostResponse
	5,  // 10: shortener.Shortener.HandleGet:output_type -> shortener.HandleGetResponse
	7,  // 11: shortener.Shortener.HandleGetUserURLs:output_type -> shortener.HandleGetUserURLsResponse
	11, // 12: shortener.Shortener.HandlePostShortenBatch:output_type -> shortener.HandlePostShortenBatchResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_app_transport_grpc_proto_shortener_proto_init() }
func file_internal_app_transport_grpc_proto_shortener_proto_init() {
	if File_internal_app_transport_grpc_proto_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleGetUserURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorrelationURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorrelationURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlePostShortenBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_app_transport_grpc_proto_shortener_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlePostShortenBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_app_transport_grpc_proto_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_app_transport_grpc_proto_shortener_proto_goTypes,
		DependencyIndexes: file_internal_app_transport_grpc_proto_shortener_proto_depIdxs,
		MessageInfos:      file_internal_app_transport_grpc_proto_shortener_proto_msgTypes,
	}.Build()
	File_internal_app_transport_grpc_proto_shortener_proto = out.File
	file_internal_app_transport_grpc_proto_shortener_proto_rawDesc = nil
	file_internal_app_transport_grpc_proto_shortener_proto_goTypes = nil
	file_internal_app_transport_grpc_proto_shortener_proto_depIdxs = nil
}
